### ISSUE TITLE
Establish structure for Services section/pages/order

### ISSUE THREAD

**Issue by elbeezy** [mattw59/guides#11]
Our goal should be to mimic the general cadence of the other primary sections like Models: introduction, creation, implementation, etc. Let's keep the section as brief as possible while including the crucial aspects of services and making sure each major topic is either on its own page or readily linkable via an anchored header.

I think we should wrap up with some more complex examples. I've noticed a few sections lacking these and (at least for me) it'd be helpful to see implementations that go beyond the trivial examples used to demonstrate isolated aspects of the Service pattern. The DOM audioplayer demo is a GREAT example and should absolutely be in this section, as well as maybe one more demonstrating the less-common and less obvious service situations like injecting a service into another service etc.

Lastly, the article about the Container and Factories seems out of place in this section. They're referenced in the discussion of DI via initializers, but they're not addressed in depth in the context of services and this bit doesn't relate or connect directly back to the rest of our content at all. I'm not sure where it would go, but that's a decision we could defer to @tomdale, @locks, @trek, @michaelrkn, etc. :)

Proposal (page names subject to change):

1. Introduction
2. Creating Services
3. Accessing Services (would cover `Ember.inject` and injection via `instance-initializer`)
4. Building with Services (the complex examples section)

**Comment by mattw59** [comment]
I think the overall outline above is solid, but I feel pretty strongly that you can't discuss services without discussing the container and factories. I can see where they don't need their own section. I just think it helps to know how the container allows services to be a singleton, and factories allow that singleton to be available in the concrete instances of those factories.

**Comment by elbeezy** [comment]
@mattw59 I think we can just mention each of those (container and factories) briefly in the introduction when discussing singletons and service lookup/instance respectively without going into depth about either concept in their own right

**Comment by mattw59** [comment]
@elbeezy I added new issues for the new titles, since two of the four old issues were no longer applicable. See #13, #14, #14, #16. I think now we just need to revise these so they have the correct content. I think many things seem to be in the wrong place.

**Comment by tomdale** [comment]
> I think the overall outline above is solid, but I feel pretty strongly that you can't discuss services without discussing the container and factories. I can see where they don't need their own section. I just think it helps to know how the container allows services to be a singleton, and factories allow that singleton to be available in the concrete instances of those factories.

I am against surfacing the container in this section. The container remains private API and I am not at all comfortable talking about making changes to the container to make changes to services since these could easily change in a future release. If there are specific use cases that we need to cover let's get those covered with a proper public API rather than sending new users down a very painful path.

**Comment by mattw59** [comment]
@tomdale Just to be clear, I'm not suggesting we advocate changing the container, just mentioning in the guide (similar to the current DI guide) that it exists and enables the services to be available across the application. And that it's a private API.

**Comment by locks** [comment]
> I think the overall outline above is solid, but I feel pretty strongly that you can't discuss services without discussing the container and factories.

I strongly disagree, we talk about services all the time and we don't need to talk about either the container or factories. I do agree that knowing that a service is a singleton is useful.

**Comment by mattw59** [comment]
OK, we'll remove any mention of them.

**Comment by tomdale** [comment]
@mattw59 In general, thinking "we should write documentation for a private API" should produce some cognitive dissonance in you. ;) By definition, private APIs are liable to change in the future, and documenting them implicitly makes them public.

However! Oftentimes there are very good reasons for wanting to tell people to use private APIs. In those instances, I would encourage you to file bugs/draft RFCs to expose public APIs that add the functionality that people need. Basically, we consider people needing to use private APIs a bug—let's get them a public API they can use without fear that it may suddenly break in a minor update.

**Comment by mattw59** [comment]
@tomdale I totally agree, and I would like to think I'd never suggest **using** a private API (heaven forbid!). My thinking was more that it could be helpful for the reader to understand how the container uses factories and manages services, without encouraging them to use the private API.

Your point about documenting a private API implicitly making that API public is well taken. I hadn't quite thought about it in that way. We'll be careful to avoid that trap. Thanks for following up.

**Comment by tomdale** [comment]
Not that I need to beat a dead horse further, but I think explaining things in terms of private APIs or specific implementation is a sign that a technical writer has been struck by the _Curse of Knowledge_. It's so easy to get pulled into explaining things in terms of how it's actually implemented, since it's the most definitionally true. But someone approaching the API for the first time is going to have a totally blank mental model, and oftentimes keeping things in terms of the high level API helps them think about solving problems more clearly.

**Comment by mattw59** [comment]
This is great insight, thank you! I could talk about this kind of stuff all day, but I suspect that's not a great use of your time. Thanks for your help, and I'll be sure to keep this in mind for future contributions.
